import { ApolloClient, gql, InMemoryCache } from '@apollo/client'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { GET_HOME_POSTS } from '../graphql/queries'
import Footer from './components/Footer'

export default function Home({ posts }) {
  return (
    <div>
      <Head>
        <title>ztkilla&apos;s blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid grid-cols-1 mx-auto container md:grid-cols-12">
        <div className="col-span-8 col-start-3 mx-auto flex-col flex gap-14 h-full">
          {posts.map((post) => {
            return (
              <Link href={'/posts/' + post.slug} key={post.slug}>
                <picture>
                  <img
                    alt={post.title}
                    src={post.thumbnail.url}
                    className="object-cover w-full h-80 object-center"
                  />
                </picture>
                <h2 className="mt-3 font-bold text-xl">{post.title}</h2>
                <p>{post.description}</p>
              </Link>
            )
          })}
        </div>
      </main>
      <Footer />
    </div>
  )
}

export async function getStaticProps() {
  const client = new ApolloClient({
    uri: 'https://api-eu-central-1-shared-euc1-02.hygraph.com/v2/cl9yahioc1ii101uobtuf63s5/master',
    cache: new InMemoryCache(),
  })

  const { data } = await client.query({
    query: GET_HOME_POSTS,
  })

  return {
    props: {
      posts: data.blogPosts,
    },
  }
}
